# brew bundle --file=~/Brewfile

# Elegant Lua unit testing
brew "busted"
# Next-generation test runner for Rust
brew "cargo-nextest"
# Improved top (interactive process viewer)
brew "htop"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Tool for linting and static analysis of Lua code
brew "luacheck"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Open-source, cross-platform JavaScript runtime environment
brew "node"
# Manage multiple Node.js versions
brew "nvm"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Opinionated Lua code formatter
brew "stylua"
# Parser generator tool
brew "tree-sitter-cli"
# Internet file retriever
brew "wget"
# Better file listing
brew "eza"
# For clearer git diffs
brew "git-delta"
# Faster than cd
brew "zoxide"
# Needed for zoxide
brew "fzf"
# Starship: https://starship.rs/
brew "starship"
# Cleaning up images/videos metadata
# exiftool -all= -o cleaned-video.mov your-video.mov
# exiftool -all= -o cleaned-image.png your-image.png
brew "exiftool"
# ffmpeg -i input.mov -c copy output.mp4
# Converting .mov to .mp4
brew "ffmpeg"


# JetBrains Mono Nerd Font, patched with icons
cask "font-jetbrains-mono-nerd-font"
# Claude desktop app
cask "claude"
